services:
  smokeping:
    image: linuxserver/smokeping
    container_name: smokeping
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Copenhagen
    volumes:
      - /srv/docker/smokeping/config.d:/config
      - /srv/docker/smokeping/data:/data
    ports:
      - 8002:80
    mem_limit: 4096m
    restart: unless-stopped
